// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointRealm.Server.Infrastructure.Persistence;

#nullable disable

namespace PointRealm.Server.Infrastructure.Migrations
{
    [DbContext(typeof(PointRealmDbContext))]
    [Migration("20260124033141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("RealmId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientInstanceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RealmId", "ClientInstanceId")
                        .IsUnique();

                    b.ToTable("PartyMembers");
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RealmId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RealmId", "Order");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.Realm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentEncounterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentQuestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.Encounter", b =>
                {
                    b.HasOne("PointRealm.Server.Domain.Entities.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PointRealm.Server.Domain.Entities.Realm", null)
                        .WithMany("Encounters")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("PointRealm.Server.Domain.Entities.Vote", "Votes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("EncounterId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("PartyMemberId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("EncounterId");

                            b1.ToTable("Votes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EncounterId");

                            b1.OwnsOne("PointRealm.Server.Domain.ValueObjects.RuneCardValue", "Value", b2 =>
                                {
                                    b2.Property<Guid>("VoteId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ValueLabel");

                                    b2.Property<decimal?>("Value")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ValueAmount");

                                    b2.HasKey("VoteId");

                                    b2.ToTable("Votes");

                                    b2.WithOwner()
                                        .HasForeignKey("VoteId");
                                });

                            b1.Navigation("Value")
                                .IsRequired();
                        });

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.PartyMember", b =>
                {
                    b.HasOne("PointRealm.Server.Domain.Entities.Realm", null)
                        .WithMany("Members")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.Quest", b =>
                {
                    b.HasOne("PointRealm.Server.Domain.Entities.Realm", null)
                        .WithMany("Quests")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.Realm", b =>
                {
                    b.OwnsOne("PointRealm.Server.Domain.ValueObjects.RealmSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("RealmId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AllowAbstain")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AutoReveal")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Deck")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HideVoteCounts")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RealmId");

                            b1.ToTable("Realms");

                            b1.WithOwner()
                                .HasForeignKey("RealmId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("PointRealm.Server.Domain.Entities.Realm", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("Members");

                    b.Navigation("Quests");
                });
#pragma warning restore 612, 618
        }
    }
}
